=== rhfogh/mxlims_data_model/mxlims/schemas/messages/MxlimsMessage.json
{
    "$schema": "https://json-schema.org/draft-07/schema",
    "description": "Message containing all possible objects, by type",
    "title": "MxlimsMessage",
    "type": "object",
    "properties": {
        "CollectionSweep": {
            "description": "Uuid:object dictionary of CollectionSweeps.",
            "title": "CollectionSweeps",
            "type": "object",
            "additionalProperties": {
                "anyOf": [
                    {
                        "$ref": "../objects/CollectionSweep.json"
                    },
                    {
                        "$ref": "../references/MxlimsRef.json"
                    }
                ]
            }
        },
        "Crystal": {
            "description": "Uuid:object dictionary of Crystals.",
            "title": "Crystals",
            "type": "object",
            "additionalProperties": {
                "anyOf": [
                    {
                        "$ref": "../objects/Crystal.json"
                    },
                    {
                        "$ref": "../references/MxlimsRef.json"
                    }
                ]
            }
        },
        "CrystallographicSample": {
            "description": "Uuid:object dictionary of CrystallographicSamples.",
            "title": "CrystallographicSamples",
            "type": "object",
            "additionalProperties": {
                "anyOf": [
                    {
                        "$ref": "../objects/CrystallographicSample.json"
                    },
                    {
                        "$ref": "../references/MxlimsRef.json"
                    }
                ]
            }
        },
        "Dewar": {
            "description": "Uuid:object dictionary of Dewars.",
            "title": "Dewars",
            "type": "object",
            "additionalProperties": {
                "anyOf": [
                    {
                        "$ref": "../objects/Dewar.json"
                    },
                    {
                        "$ref": "../references/MxlimsRef.json"
                    }
                ]
            }
        },
        "DropRegion": {
            "description": "Uuid:object dictionary of DropRegions.",
            "title": "DropRegions",
            "type": "object",
            "additionalProperties": {
                "anyOf": [
                    {
                        "$ref": "../objects/DropRegion.json"
                    },
                    {
                        "$ref": "../references/MxlimsRef.json"
                    }
                ]
            }
        },
        "MxExperiment": {
            "description": "Uuid:object dictionary of MxExperiments.",
            "title": "MxExperiments",
            "type": "object",
            "additionalProperties": {
                "anyOf": [
                    {
                        "$ref": "../objects/MxExperiment.json"
                    },
                    {
                        "$ref": "../references/MxlimsRef.json"
                    }
                ]
            }
        },
        "MxProcessing": {
            "description": "Uuid:object dictionary of MxProcessings.",
            "title": "MxProcessings",
            "type": "object",
            "additionalProperties": {
                "anyOf": [
                    {
                        "$ref": "../objects/MxProcessing.json"
                    },
                    {
                        "$ref": "../references/MxlimsRef.json"
                    }
                ]
            }
        },
        "Pin": {
            "description": "Uuid:object dictionary of Pins.",
            "title": "Pins",
            "type": "object",
            "additionalProperties": {
                "anyOf": [
                    {
                        "$ref": "../objects/Pin.json"
                    },
                    {
                        "$ref": "../references/MxlimsRef.json"
                    }
                ]
            }
        },
        "PinPosition": {
            "description": "Uuid:object dictionary of PinPositions.",
            "title": "PinPositions",
            "type": "object",
            "additionalProperties": {
                "anyOf": [
                    {
                        "$ref": "../objects/PinPosition.json"
                    },
                    {
                        "$ref": "../references/MxlimsRef.json"
                    }
                ]
            }
        },
        "Plate": {
            "description": "Uuid:object dictionary of Plates.",
            "title": "Plates",
            "type": "object",
            "additionalProperties": {
                "anyOf": [
                    {
                        "$ref": "../objects/Plate.json"
                    },
                    {
                        "$ref": "../references/MxlimsRef.json"
                    }
                ]
            }
        },
        "PlateWell": {
            "description": "Uuid:object dictionary of PlateWells.",
            "title": "PlateWells",
            "type": "object",
            "additionalProperties": {
                "anyOf": [
                    {
                        "$ref": "../objects/PlateWell.json"
                    },
                    {
                        "$ref": "../references/MxlimsRef.json"
                    }
                ]
            }
        },
        "Puck": {
            "description": "Uuid:object dictionary of Pucks.",
            "title": "Pucks",
            "type": "object",
            "additionalProperties": {
                "anyOf": [
                    {
                        "$ref": "../objects/Puck.json"
                    },
                    {
                        "$ref": "../references/MxlimsRef.json"
                    }
                ]
            }
        },
        "ReflectionSet": {
            "description": "Uuid:object dictionary of ReflectionSets.",
            "title": "ReflectionSets",
            "type": "object",
            "additionalProperties": {
                "anyOf": [
                    {
                        "$ref": "../objects/ReflectionSet.json"
                    },
                    {
                        "$ref": "../references/MxlimsRef.json"
                    }
                ]
            }
        },
        "Shipment": {
            "description": "Uuid:object dictionary of Shipments.",
            "title": "Shipments",
            "type": "object",
            "additionalProperties": {
                "anyOf": [
                    {
                        "$ref": "../objects/Shipment.json"
                    },
                    {
                        "$ref": "../references/MxlimsRef.json"
                    }
                ]
            }
        },
        "WellDrop": {
            "description": "Uuid:object dictionary of WellDrops.",
            "title": "WellDrops",
            "type": "object",
            "additionalProperties": {
                "anyOf": [
                    {
                        "$ref": "../objects/WellDrop.json"
                    },
                    {
                        "$ref": "../references/MxlimsRef.json"
                    }
                ]
            }
        }
    }
}

=== rhfogh/mxlims_data_model/docs/examples/Shipment_plates.json
{
  "Shipment": {
    "4a96f23d-0f3c-2c96-b3d1-b908984ec709": {
      "proposalCode": "mx4025",

      "comment": "Example of an MXLIMS plate shipment",
      "labContactOutbound": {
        "name": "Bob"
      },
      "labContactReturn": {
        "name": "Bob"
      },
      "version": "0.6.1",
      "mxlimsType": "Shipment",
      "mxlimsBaseType": "LogisticalSample",
      "uuid": "4a96f23d-0f3c-2c96-b3d1-b908984ec709"
    }
  },
  "Plate": {
    "4a96f23a-dce0-2560-baac-f1b23ec9e0cb": {
      "barcode": "9098",
      "plateType": {
        "numberRows": 8,
        "numberColumns": 12,
        "numberSubPositions": 3,
        "dropMapping": "12,3R"
      },
      "containerRef": { "$ref": "#/Shipment/4a96f23d-0f3c-2c96-b3d1-b908984ec709" },
      "version": "0.6.1",
      "mxlimsType": "Plate",
      "mxlimsBaseType": "LogisticalSample",
      "uuid": "4a96f23a-dce0-2560-baac-f1b23ec9e0cb"
    }
  },
  "PlateWell": {
    "4a96f23a-dce0-2560-baac-f1b23ec9e0aa": {
      "rowNumber": 1,
      "columnNumber": 1,
      "containerRef": { "$ref": "#/Plate/4a96f23a-dce0-2560-baac-f1b23ec9e0cb" },
      "version": "0.6.1",
      "mxlimsType": "PlateWell",
      "mxlimsBaseType": "LogisticalSample",
      "uuid": "4a96f23a-dce0-2560-baac-f1b23ec9e0aa"
    }
  },
  "WellDrop": {
    "4a96f23a-dce0-2560-baac-f1b23ec9e0dd": {
      "dropNumber": 1,
      "containerRef": { "$ref": "#/PlateWell/4a96f23a-dce0-2560-baac-f1b23ec9e0aa" },
      "sampleRef": { "$ref": "#/CrystallographicSample/4a96f23a-dce0-2560-baac-f1b23ec9e022" },
      "version": "0.6.1",
      "mxlimsType": "WellDrop",
      "mxlimsBaseType": "LogisticalSample",
      "uuid": "4a96f23a-dce0-2560-baac-f1b23ec9e0dd"
    }
  },
  "CrystallographicSample": {
    "4a96f23a-dce0-2560-baac-f1b23ec9e022": {
      "name": "LMTIM_9098A01d1c1",
      "macromolecule": {
        "acronym": "LMTIM",
        "role": "target"
      },
      "version": "0.6.1",
      "mxlimsType": "CrystallographicSample",
      "mxlimsBaseType": "PreparedSample",
      "uuid": "4a96f23a-dce0-2560-baac-f1b23ec9e022"
    }
  }
}
